version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5001:5000"
    env_file:
      - .env
    depends_on:
      - database
    command: node index.js

  frontend:
    build:
      context: ./frontend
      target: production   # Use the nginx production stage from your Dockerfile
    ports:
      - "3001:80"          # Expose nginx port 80 to host port 3001
    depends_on:
      - backend
    # No volumes or command overrides for production

  database:
    image: mongo
    container_name: mongo_db
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
